[project]
name = "mason-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "mlflow",
    "joblib",
    "jupyter",
    "ipykernel"
]
